language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t jheedocker/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jheedocker/react-test-app npm run test

after_success:
  - docker build -t jheedocker/docker-frontend ./frontend
  - docker build -t jheedocker/docker-backend ./backend
  - docker build -t jheedocker/docker-nginx ./nginx
# 레파지토리 > Settings > Environment Variables 에 도커허브id와 비번 저장
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
# travis ci 연동되려면 Plan 선택하고 결제해야 서비스 가능
  - docker push jheedocker/docker-frontend
  - docker push jheedocker/docker-backend
  - docker push jheedocker/docker-nginx